#!/usr/bin/env python3
"""Generate a broad, self-checking play-harness survey from the source planet
data — the automated-discovery front line.

Where hand-authored probes (and invariant-survey.play) check a handful of
coordinates a human picked, this samples MANY coordinates straight from
output/<world>/planet_data.npz and asserts the universal invariant for each
feature class. That turns every single-point bug the AI hunt found into a
whole-class gate:

  * frozen lake  -> must be walkable ice (grounded, not underwater, dry)   [R3]
  * inland land  -> must be walkable (grounded)                            [fall-through-world]
  * high peak    -> must still support the player (grounded)
  * liquid lake  -> must read as water (has_water)
  * ocean        -> must submerge a settling player (has_water, underwater)[R2/immersion]

Only INTERIOR cells are sampled (every valid neighbour shares the class) so a
point feature can't land just off its edge after the icosphere->cube-face
resample and fail spuriously. Sampling is deterministic (sorted indices, even
stride) so the emitted survey is reproducible and diffable.

Usage:
  python viewer/scripts/gen_survey.py [--world output/seed42_r8]
                                      [--out viewer/scripts/auto-survey.play]
                                      [--per N]
Then run the result:
  ./viewer/target/release/examples/play.exe viewer/scripts/auto-survey.play
A non-zero exit means a coordinate violated its class invariant — a candidate
bug to investigate (or a genuine feature-edge false alarm to tighten out).
"""
import argparse
import numpy as np
from pathlib import Path


def interior(mask, nb):
    """Cells in `mask` whose every VALID neighbour is also in `mask`."""
    valid = nb >= 0
    nbm = np.where(valid, mask[np.where(valid, nb, 0)], True)
    return mask & nbm.all(axis=1)


def sample(idx, count):
    """Deterministic even-stride pick of `count` indices from sorted `idx`."""
    idx = np.sort(idx)
    if len(idx) <= count:
        return idx
    stride = len(idx) / count
    return idx[np.floor(np.arange(count) * stride).astype(int)]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--world", default="output/seed42_r8")
    ap.add_argument("--out", default="viewer/scripts/auto-survey.play")
    ap.add_argument("--per", type=int, default=16,
                    help="base samples per class (peaks/ocean scaled down)")
    args = ap.parse_args()

    d = np.load(Path(args.world) / "planet_data.npz")
    latd = np.degrees(d["lat"])
    lond = np.degrees(d["lon"])
    tmean = d["temp_c_monthly"].mean(axis=0)
    elev = d["elevation_km"]
    nb = d["neighbors"]
    ocean = d["is_ocean"]
    lake = d["lake_id"] >= 0
    river = d["river"]
    land = ~ocean

    # feature masks (interior-only where a point feature could miss its edge).
    # Below-freezing water (lake OR sea) renders as a solid ice sheet you walk
    # ON, not liquid — so it is split out from open water and gated as ice.
    dry_land = land & ~lake & ~river
    frozen_lake = interior(lake & (tmean < -6.0), nb)
    sea_ice = interior(ocean & (tmean < -6.0), nb)
    liquid_lake = interior(lake & (tmean > 6.0), nb)
    inland = interior(dry_land, nb)
    deep_ocean = interior(ocean & (tmean > 2.0), nb)
    # peaks: interior dry land in the top 2% by elevation
    hi = elev >= np.quantile(elev[dry_land], 0.98)
    peaks = interior(dry_land & hi, nb)

    # (class label, index-mask, count, [(field, op, value), ...], settle secs)
    P = args.per
    classes = [
        ("inland-land", inland,      P,        [("grounded", "==", "true")], 8),
        ("high-peak",   peaks,       max(6, P // 2),
                                                [("grounded", "==", "true")], 8),
        ("frozen-lake", frozen_lake, P,        [("grounded", "==", "true"),
                                                 ("underwater", "==", "false"),
                                                 ("has_water", "==", "false")], 8),
        ("sea-ice",     sea_ice,     max(8, P // 2),
                                                [("grounded", "==", "true"),
                                                 ("underwater", "==", "false"),
                                                 ("has_water", "==", "false")], 8),
        ("liquid-lake", liquid_lake, max(8, P // 2),
                                                [("has_water", "==", "true")], 10),
        ("ocean",       deep_ocean,  max(6, P // 2),
                                                [("has_water", "==", "true"),
                                                 ("underwater", "==", "true")], 12),
    ]

    lines = [
        "# AUTO-GENERATED by viewer/scripts/gen_survey.py — do not hand-edit.",
        f"# Broad invariant sweep sampled from {args.world}/planet_data.npz.",
        "# Each block settles the player at a real feature cell and asserts the",
        "# universal invariant for that class. A failure = a candidate bug.",
        "",
    ]
    total = 0
    for label, mask, count, asserts, settle in classes:
        idx = sample(np.flatnonzero(mask), count)
        lines.append(f"# ===== {label}: {len(idx)} cells "
                     f"(of {int(mask.sum())} interior) =====")
        for i in idx:
            total += 1
            lines.append(f"# {label} @ cell {int(i)} tmean={tmean[i]:.1f}C "
                         f"elev={elev[i]:.3f}km")
            lines.append(f"teleport {latd[i]:.4f} {lond[i]:.4f} 0.05")
            lines.append("mode walk")
            lines.append(f"wait {settle}")
            for field, op, val in asserts:
                lines.append(f"assert {field} {op} {val}")
            lines.append("")
    Path(args.out).write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.out}: {total} probes across {len(classes)} classes")


if __name__ == "__main__":
    main()
