#!/usr/bin/env python3
"""The sky reel: pins today's sun/moon/atmosphere appearance from Neisor.

SOLAR.md non-negotiable #1: the tuned sky look (sun disc + halo, moon
disc + phase among stars, sunset gradient) must survive the physical-
bodies rework byte-recognizably. Like world_reel.py this is a change
detector diffed against a human-blessed baseline, plus presence lints
so a pose that silently loses its disc fails even without a baseline.

Usage (from viewer/):
  python scripts/sky_reel.py            render + lint + diff vs accepted
  python scripts/sky_reel.py --accept   bless current as the baseline
Exit codes: 0 clean, 3 findings to review.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# name, cam(lat, lon, alt), look(yaw, pitch), sun(lat, lon)
# Moon rides anti-sun tilted 18 deg about world X (renderer.rs), so a
# pinned sun pins the moon: for sun (10, 0) the moon zenith sits at
# (-9.5, 176.9) - the moon poses stand at that point and look up.
POSES = [
    ("sun_zenith",   (10.0, 0.0, 0.05),     (0, 75),   (10.0, 0.0)),
    ("sunset_west",  (10.0, 91.0, 0.05),    (-90, 3),  (10.0, 0.0)),
    ("dusk_gradient", (10.0, 95.0, 0.05),   (-90, 10), (10.0, 0.0)),
    ("moon_zenith",  (-9.5, 176.9, 0.05),   (0, 75),   (10.0, 0.0)),
    ("night_stars",  (-9.5, 176.9, 0.05),   (120, 35), (10.0, 0.0)),
]

CHANGE_MEAN = 1.0
CHANGE_FRAC = 0.01
MOON_ROI_HALF = 48
MOON_ROI_MEAN = 1.0
MOON_ROI_FRAC = 0.05


def build_play(path: Path):
    lines = ["# generated by sky_reel.py", "mode fly",
             "weather pin 0.0 0.0", "weather time 0"]
    for name, (lat, lon, alt), (yaw, pitch), (slat, slon) in POSES:
        lines += [
            f"sun {slat} {slon}",
            f"teleport {lat} {lon} {alt}",
            f"look {yaw} {pitch}",
            f"shot {name}",
        ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def lint(name: str, im: np.ndarray) -> list[str]:
    """Presence checks: each pose must keep its celestial furniture."""
    out = []
    lum = im.max(axis=2)
    if name == "sun_zenith":
        if (lum > 250).sum() < 80:
            out.append(f"{name}: sun disc missing (<80 px above 250)")
    if name == "sunset_west":
        if (lum > 240).sum() < 30:
            out.append(f"{name}: setting sun disc missing")
    if name == "moon_zenith":
        # pale gray disc: bright-ish pixels in the upper 2/3, well above
        # the star point count
        disc = (lum > 120).sum()
        if disc < 60:
            out.append(f"{name}: moon disc missing (<60 px above 120)")
    if name == "night_stars":
        stars = ((lum > 100) & (lum < 255)).sum()
        if stars < 40:
            out.append(f"{name}: starfield missing (<40 star px)")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--accept", action="store_true")
    ap.add_argument("--skip-render", action="store_true")
    args = ap.parse_args()

    viewer = Path(__file__).resolve().parent.parent
    reel = viewer / "interchange" / "skyreel"
    current = reel / "current"
    accepted = reel / "accepted"
    run_dir = viewer / "interchange" / "runs" / "sky-reel"
    play = viewer / "scripts" / "sky-reel.play"

    if not args.skip_render:
        build_play(play)
        exe = viewer / "target" / "release" / "examples" / "play.exe"
        r = subprocess.run([str(exe), str(play)], cwd=viewer,
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout[-1500:] + r.stderr[-1500:])
            raise SystemExit(f"sky reel render failed ({r.returncode})")
        current.mkdir(parents=True, exist_ok=True)
        for name, *_ in POSES:
            shutil.copyfile(run_dir / f"{name}.png", current / f"{name}.png")

    findings = []
    for name, *_ in POSES:
        cur_p = current / f"{name}.png"
        if not cur_p.exists():
            findings.append(f"{name}: MISSING current frame")
            continue
        im = np.asarray(Image.open(cur_p).convert("RGB"), dtype=np.float64)
        findings += lint(name, im)
        acc_p = accepted / f"{name}.png"
        if acc_p.exists():
            old = np.asarray(Image.open(acc_p).convert("RGB"), dtype=np.float64)
            if old.shape == im.shape:
                d = np.abs(old - im).max(axis=2)
                mean, frac = float(d.mean()), float((d > 6).mean())
                if mean > CHANGE_MEAN or frac > CHANGE_FRAC:
                    findings.append(
                        f"{name}: CHANGED vs accepted (mean {mean:.3f}, "
                        f"frac {frac:.4f})"
                    )
                if name == "moon_zenith":
                    # The physical disc is only ~0.04% of the frame, so a
                    # whole-frame 1% detector mathematically cannot see a new
                    # face. This fixed-pose ROI covers disc + tight halo and
                    # leaves the global threshold intact for all other sky.
                    cy, cx = int(im.shape[0] * 0.286), im.shape[1] // 2
                    r = MOON_ROI_HALF
                    roi = d[cy-r:cy+r, cx-r:cx+r]
                    roi_mean = float(roi.mean())
                    roi_frac = float((roi > 6).mean())
                    if roi_mean > MOON_ROI_MEAN or roi_frac > MOON_ROI_FRAC:
                        findings.append(
                            f"{name}: CHANGED moon ROI (mean {roi_mean:.3f}, "
                            f"frac {roi_frac:.4f})"
                        )

    if args.accept:
        accepted.mkdir(parents=True, exist_ok=True)
        for name, *_ in POSES:
            src = current / f"{name}.png"
            if src.exists():
                shutil.copyfile(src, accepted / f"{name}.png")
        print(f"accepted: {len(POSES)} sky poses blessed")
        return

    if findings:
        print(f"SKY REEL: {len(findings)} finding(s):")
        for f in findings:
            print(" ", f)
        sys.exit(3)
    print(f"SKY REEL: all {len(POSES)} poses clean")


if __name__ == "__main__":
    main()
