#!/usr/bin/env python3
"""Mesh<->voxel appearance divergence meter (Austin's image-diff idea).

Renders every pose twice through the play harness — once normal (voxel
patch on), once with `voxels off` (pure heightfield mesh) — and image-diffs
the pairs. Everything outside the voxel patch renders identically (the
harness is deterministic), so the nonzero-diff region IS the patch: its
statistics measure exactly how much appearance the mesh->voxel handoff
changes, per pose, in numbers.

This is a MEASURING INSTRUMENT, not an optimization target: use it to find
the worst poses, to check that a color/texture change moved mesh and blocks
together, and to catch regressions. Do not tune renders to minimize the
metric blindly — muting detail on both sides "improves" the number while
making the game worse (Goodhart). Judgment stays human.

Usage:  python scripts/sync_diff.py [--skip-render] [--label NAME]
        (from viewer/; needs target/release/examples/play.exe built)

Outputs interchange/runs/sync-diff/: the frame pairs, *_diff.png heatmaps,
report.md + report.json (per-pose metrics table).
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# The standing pose table. Poses are Austin's own photographed spots plus
# survey picks — low altitude (inside voxel range), pinned near-noon sun at
# a slight angle so shading relief shows, pinned mostly-clear sky. Extend
# freely; names are stable so reports stay comparable across commits.
POSES = [
    # name,            lat,        lon,        alt_km,  yaw,   pitch, note
    ("river_low",      15.024204,  17.661741,  0.154,  -75.4, -21.3, "wide river, both banks"),
    ("river_mid",      15.024204,  17.649000,  0.199,  -98.0, -28.0, "river reach from above"),
    ("lake_shore",     13.346000,  -4.806000,  0.443,  -72.0, -55.0, "lake border (V-5 site)"),
    ("savanna",         5.560000,  31.741000,  0.196,  150.0, -40.0, "open savanna"),
    ("beach",           8.097000, -35.673000,  0.060,   77.0, -30.0, "coast / beach dither"),
    ("jungle",         -0.906000, -67.804000,  0.094, -210.0, -17.0, "dense forest + impostors"),
    ("taiga",          47.861000,  14.399000,  0.592,  -49.0, -62.0, "snowline, high pitch-down"),
    ("desert",          0.870000, -89.800000,  0.120,  -35.0, -30.0, "dune field"),
    ("peak",           69.000000, 122.000000,  0.350,   20.0, -35.0, "steep alpine slopes"),
    ("valley",          4.990000, -29.403000,  0.250,  -10.0, -40.0, "carved valley walls"),
    ("groves",          3.960000, -32.560000,  0.150,   60.0, -25.0, "open groves, scattered trees"),
    ("ice_top",        83.997000,  40.220000,  0.200,    0.0, -35.0, "polar ice sheet"),
    ("frozen_lake",    51.180000,  85.830000,  0.300,    0.0, -50.0, "seasonal frozen lake"),
    ("karst",          13.346000,  -4.807000,  0.289,  -78.0, -55.0, "flooded-cave breach field (V-10 hint)"),
    # A deep-ocean census point keeps the control free of the distant coastal
    # pixels that had crept into the old 24.482/24.967 horizon. This is a pure
    # water comparison: mesh and voxel renders must be exactly identical.
    ("sea_calib",     -51.425100,  24.460700,  0.120,    0.0, -30.0, "open sea: must stay ~0 (calibration)"),
]

NOISE_FLOOR = 2  # |delta| <= this (out of 255) counts as identical


def build_play(poses, out_path: Path, season: float):
    lines = ["# generated by sync_diff.py — do not hand-edit", "mode fly"]
    lines.append(f"weather season {season:.8f}")
    for name, lat, lon, alt, yaw, pitch, _ in poses:
        sun_lat = max(-23.0, min(23.0, lat))
        sun_lon = lon - 15.0
        lines += [
            f"teleport {lat:.6f} {lon:.6f} {alt:.6f}",
            f"look {yaw:.2f} {pitch:.2f}",
            f"sun {sun_lat:.2f} {sun_lon:.2f}",
            "weather pin 0.10 0.0",
            f"shot {name}_vox",
            "voxels off",
            f"shot {name}_mesh",
            "voxels on",
        ]
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def diff_pair(vox_png: Path, mesh_png: Path, heat_png: Path):
    a = np.asarray(Image.open(vox_png).convert("RGB"), dtype=np.int16)
    b = np.asarray(Image.open(mesh_png).convert("RGB"), dtype=np.int16)
    if a.shape != b.shape:
        raise SystemExit(f"size mismatch: {vox_png} {a.shape} vs {mesh_png} {b.shape}")
    d = np.abs(a - b).max(axis=2)  # worst channel per pixel
    mask = d > NOISE_FLOOR
    n = int(mask.sum())
    total = d.size
    # luminance, signed: + means the voxel render is brighter there
    lum = (a.astype(np.float64) @ [0.2126, 0.7152, 0.0722]) - (
        b.astype(np.float64) @ [0.2126, 0.7152, 0.0722]
    )
    m = {
        "divergent_frac": round(n / total, 4),
        "mean_delta": round(float(d[mask].mean()), 2) if n else 0.0,
        "p95_delta": int(np.percentile(d[mask], 95)) if n else 0,
        "max_delta": int(d.max()),
        "signed_lum": round(float(lum[mask].mean()), 2) if n else 0.0,
    }
    # heatmap: mesh frame dimmed, divergence in red (intensity = delta)
    heat = (np.asarray(Image.open(mesh_png).convert("RGB"), dtype=np.float64) * 0.35)
    heat[..., 0] = np.maximum(heat[..., 0], np.minimum(d * 3.0, 255.0))
    Image.fromarray(heat.astype(np.uint8)).save(heat_png)
    return m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-render", action="store_true", help="diff existing frames only")
    ap.add_argument("--label", default="", help="tag stored in report.json (e.g. commit)")
    ap.add_argument("--season", type=float, default=0.45,
                    help="orbital season fraction for both renderers")
    ap.add_argument(
        "--at",
        nargs="+",
        type=float,
        metavar="N",
        help="ad-hoc single pose: LAT LON ALT_KM [YAW PITCH] - renders and diffs "
        "just this pose (hunt tool; agents can't press V)",
    )
    args = ap.parse_args()
    if args.at:
        lat, lon, alt = args.at[0], args.at[1], args.at[2]
        yaw = args.at[3] if len(args.at) > 3 else 0.0
        pitch = args.at[4] if len(args.at) > 4 else -80.0
        global POSES
        POSES = [("adhoc", lat, lon, alt, yaw, pitch, f"--at {lat} {lon}")]

    viewer = Path(__file__).resolve().parent.parent
    suffix = "" if abs(args.season - 0.45) < 1e-12 else f"-season-{args.season:.2f}"
    run_dir = viewer / "interchange" / "runs" / f"sync-diff{suffix}"
    play = viewer / "scripts" / f"sync-diff{suffix}.play"
    build_play(POSES, play, args.season)

    if not args.skip_render:
        exe = viewer / "target" / "release" / "examples" / "play.exe"
        r = subprocess.run([str(exe), str(play)], cwd=viewer, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout[-2000:] + r.stderr[-2000:])
            raise SystemExit(f"play run failed ({r.returncode})")

    rows, results = [], {}
    for name, *_rest, note in [(p[0], *p[1:-1], p[-1]) for p in POSES]:
        vox, mesh = run_dir / f"{name}_vox.png", run_dir / f"{name}_mesh.png"
        if not vox.exists() or not mesh.exists():
            raise SystemExit(f"missing frames for {name} — render first")
        m = diff_pair(vox, mesh, run_dir / f"{name}_diff.png")
        results[name] = m | {"note": note}
        rows.append(
            f"| {name} | {m['divergent_frac']*100:.1f}% | {m['mean_delta']} "
            f"| {m['p95_delta']} | {m['signed_lum']:+.1f} | {note} |"
        )

    label = f" ({args.label})" if args.label else ""
    report = "\n".join(
        [
            f"# mesh<->voxel sync-diff{label}",
            "",
            "delta units: 8-bit channel values. divergent = pixels where the two",
            "renders differ (the voxel patch + impostor swaps). signed_lum > 0 =",
            "voxel render brighter than mesh there.",
            "",
            "| pose | divergent | mean d | p95 d | lum bias | note |",
            "|---|---|---|---|---|---|",
            *rows,
            "",
        ]
    )
    (run_dir / "report.md").write_text(report, encoding="utf-8")
    (run_dir / "report.json").write_text(
        json.dumps({"label": args.label, "poses": results}, indent=1), encoding="utf-8"
    )
    print(report)


if __name__ == "__main__":
    main()
