#!/usr/bin/env python3
"""Feature-coordinate query — find REAL coordinates for a named feature class
straight from planet_data, so play scripts and hunt missions jump to a feature
instead of guessing a lat/lon and landing on dry ground. Play scripts can't
branch on state, so pre-resolved coordinates are how a weak operator reaches a
frozen lake or a river on the first try.

  python viewer/scripts/where.py                    # list classes + cell counts
  python viewer/scripts/where.py frozen-lake        # a spread across the planet
  python viewer/scripts/where.py river --near 20 120 --count 5   # nearest to pt
  python viewer/scripts/where.py --manifest         # write scripts/feature-coords.md

Classes come from gen_survey.feature_masks (the single shared definition), so
`where.py river` and the auto-survey agree on what a river is.
"""
import argparse
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_survey import feature_masks, sample  # noqa: E402

ALIASES = {"lake": "liquid-lake", "ice": "frozen-lake", "land": "inland-land",
           "peak": "high-peak", "sea": "ocean"}


def latlon_deg(d):
    return np.degrees(d["lat"]), np.degrees(d["lon"])


def pick(idx, xyz, near, count):
    """Coordinates for `count` cells of a class: nearest to `near` if given,
    else an even spread over the sorted index (deterministic)."""
    if near is not None:
        rlat, rlon = np.radians(near)
        v = np.array([np.cos(rlat) * np.cos(rlon),
                      np.cos(rlat) * np.sin(rlon), np.sin(rlat)])
        order = idx[np.argsort(-(xyz[idx] @ v))]
        return order[:count]
    return sample(idx, count)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("feature", nargs="?", help="feature class (see list)")
    ap.add_argument("--world", default="output/seed42_r8")
    ap.add_argument("--near", nargs=2, type=float, metavar=("LAT", "LON"))
    ap.add_argument("--count", type=int, default=8)
    ap.add_argument("--manifest", action="store_true",
                    help="write viewer/scripts/feature-coords.md and exit")
    args = ap.parse_args()

    d = np.load(Path(args.world) / "planet_data.npz")
    latd, lond = latlon_deg(d)
    xyz = d["xyz"].astype(float)
    masks = feature_masks(d)

    if args.manifest:
        rows = ["# Feature coordinates (auto-generated by where.py)",
                "",
                f"Representative teleport targets sampled from `{args.world}/"
                "planet_data.npz`. Regenerate with `python viewer/scripts/"
                "where.py --manifest`.",
                ""]
        for name, mask in masks.items():
            idx = pick(np.flatnonzero(mask), xyz, None, 6)
            rows.append(f"### {name} ({int(mask.sum())} cells)")
            for i in idx:
                rows.append(f"- `teleport {latd[i]:.3f} {lond[i]:.3f}` "
                            f"(cell {int(i)})")
            rows.append("")
        out = Path("viewer/scripts/feature-coords.md")
        out.write_text("\n".join(rows), encoding="utf-8")
        print(f"wrote {out}")
        return

    if not args.feature:
        print("feature classes (cells):")
        for name, mask in masks.items():
            print(f"  {name:<14} {int(mask.sum()):>7}")
        print("aliases:", ", ".join(f"{k}->{v}" for k, v in ALIASES.items()))
        return

    name = ALIASES.get(args.feature, args.feature)
    if name not in masks:
        sys.exit(f"unknown feature `{args.feature}`; valid: "
                 + ", ".join(masks) + " (+ aliases " + ", ".join(ALIASES) + ")")
    idx = pick(np.flatnonzero(masks[name]), xyz, args.near, args.count)
    if not len(idx):
        sys.exit(f"no `{name}` cells in {args.world}")
    for i in idx:
        print(f"teleport {latd[i]:.3f} {lond[i]:.3f}   # {name} cell {int(i)}")


if __name__ == "__main__":
    main()
