#!/usr/bin/env python3
"""The world reel: a standing pose table covering every water/biome class,
rendered deterministically and DIFFED AGAINST THE LAST ACCEPTED REEL.

This is a change detector, not a quality metric: after any terrain/water
merge, changed poses are flagged with per-pose stats and it is a human/AI
job to explain each change or fix it. It systematizes what Andrew's
field-flying caught this week (regression zoos invisible to census,
colcensus, and sync-diff, because both renderers agreed on the defect).

Every frame also runs FRAME LINT - screen-space heuristics for defect
classes that bit us:
  VOID   clusters of near-black pixels below the horizon in a daytime
         shot (see-through cracks, missing geometry)
  GRID   strong axis-aligned periodicity in water regions (per-quad
         shading seams reading as a checkerboard)

Usage (from viewer/):
  python scripts/world_reel.py            render + lint + diff vs accepted
  python scripts/world_reel.py --accept   bless the current reel as accepted
  python scripts/world_reel.py --skip-render   re-diff existing frames
Exit codes: 0 clean, 3 = changes/lint findings to review (never blocks a
human; missions treat 3 as "explain every flagged pose in FINDINGS.md").
"""

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# name, lat, lon, alt_km, yaw, pitch  (sun pinned near-noon per pose; weather
# pinned clear: the reel isolates WORLD changes, not sky ones)
POSES = [
    # the regression-dossier zones (A-4/A-5 reverts, 2026-07-11)
    ("dossier_shore",   13.348,  -4.807, 0.011, 178, -19),
    ("dossier_dlake",   13.346,  -4.807, 0.064, 113, -64),
    ("dossier_ponds",   12.199, -44.827, 0.100, -90, -45),
    ("dossier_band",    13.013,  -4.546, 0.012, 163, -12),
    # water classes
    ("karst_field",     13.346,  -4.807, 0.289, -78, -55),
    ("river_wide",      15.024,  17.662, 0.154, -75, -21),
    ("river_mouth",      7.042,  33.477, 0.300, -55, -16),
    ("river_valley",     4.990, -29.403, 0.250, -10, -40),
    ("waterfall_site",   9.79546, 107.60747, 3.000, 84.75, -68),
    ("pond_country",    -0.798, -67.941, 0.150,  40, -35),
    ("lake_archi",      16.601, -12.222, 3.000,   0, -70),
    ("inland_sea",      20.633, 127.615, 8.000,   0, -75),
    ("coast_beach",      8.097, -35.673, 0.060,  77, -30),
    ("frozen_lake",     51.180,  85.830, 0.300,   0, -50),
    ("sea_ice",         83.997,  40.220, 0.200,   0, -35),
    # biome/terrain classes
    ("ecotone_corner",  16.684, -23.367, 0.414, -91, -80),
    ("desert",           0.870, -89.800, 0.120, -35, -30),
    ("savanna",          1.510,  40.490, 0.150, 150, -40),
    ("jungle",          -0.906, -67.804, 0.094,-210, -17),
    ("taiga",           47.861,  14.399, 0.592, -49, -62),
    ("peak",            69.000, 122.000, 0.800,  20, -35),
    ("groves",           3.960, -32.560, 0.150,  60, -25),
    # range checks
    ("mid_altitude",    15.024,  17.650, 6.000, -90, -60),
    ("orbital_coast",   15.238, 150.848, 291.4, 146, -86),
    ("orbital_biomes",  42.765,  38.439, 288.2, -64, -85),
]

SUMMER_POSES = [
    ("frozen_lake_summer", 51.180, 85.830, 0.300, 0, -50),
    ("sea_ice_summer", 83.997, 40.220, 0.200, 0, -35),
]

# name, moon-local lat/lon, altitude km, local yaw/pitch. Moon poses use the
# physical epoch Sun; pinned art directions are observer-relative and are not
# valid while the camera itself moves between bodies.
# These are P2 additions and deliberately have no accepted baseline yet.
MOON_POSES = [
    ("moon_orbit_face", 10.0, 40.0, 1700.0, 0, -86),
    ("moon_low_flyby", 35.4023, 20.0000, 8.0, -90, -20),
]
ALL_POSES = [*POSES, *SUMMER_POSES, *MOON_POSES]

CHANGE_MEAN = 1.0   # mean |delta| over the frame that counts as "changed"
CHANGE_FRAC = 0.01  # or >1% of pixels differing by >6


def build_play(path: Path):
    lines = [
        "# generated by world_reel.py",
        "mode fly",
        "weather pin 0.10 0.0",
        "weather time 0",
        "weather season 0.45",
    ]
    for name, lat, lon, alt, yaw, pitch in POSES:
        sun_lat = max(-23.0, min(23.0, lat))
        lines += [
            f"teleport {lat} {lon} {alt}",
            f"look {yaw} {pitch}",
            f"sun {sun_lat:.2f} {lon - 15.0:.2f}",
            f"shot {name}",
        ]
    lines.append("weather season 0.55")
    for name, lat, lon, alt, yaw, pitch in SUMMER_POSES:
        sun_lat = max(-23.0, min(23.0, lat))
        lines += [
            f"teleport {lat} {lon} {alt}",
            f"look {yaw} {pitch}",
            f"sun {sun_lat:.2f} {lon - 15.0:.2f}",
            f"shot {name}",
        ]
    lines.append("weather season 0.45")
    lines.append("sun physical")
    for index, (name, lat, lon, alt, yaw, pitch) in enumerate(MOON_POSES):
        lines += [
            f"moonpose {lat} {lon} {alt} {yaw} {pitch}",
            *( ["focus free"] if index == 1 else [] ),
            f"shot {name}",
        ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def lint_void(im: np.ndarray) -> tuple[int, float]:
    """Largest connected near-black blob below the horizon band, plus the
    near-black fraction. Daytime pinned sun: real shadow floors are dim but
    not black; voids (sky-through-cracks at z=0 clear color, unlit gaps)
    are."""
    h = im.shape[0]
    below = im[int(h * 0.45):, :, :]
    dark = (below.max(axis=2) < 14).astype(np.uint8)
    frac = float(dark.mean())
    # cheap 4-connected blob size via repeated dilation-free row scan:
    # label runs per row, merge with the row above (two-pass union small)
    biggest = 0
    prev = {}
    labels = {}
    parent = {}

    def find(a):
        while parent.get(a, a) != a:
            parent[a] = parent.get(parent[a], parent[a])
            a = parent[a]
        return a

    nxt = 0
    for y in range(dark.shape[0]):
        row = dark[y]
        cur = {}
        x = 0
        w = dark.shape[1]
        while x < w:
            if row[x]:
                x2 = x
                while x2 < w and row[x2]:
                    x2 += 1
                lbl = None
                for px in range(x, x2):
                    if px in prev:
                        r = find(prev[px])
                        if lbl is None:
                            lbl = r
                        elif r != lbl:
                            parent[find(r)] = find(lbl)
                for px in range(x, x2):
                    if lbl is None:
                        lbl = nxt
                        nxt += 1
                    cur[px] = lbl
                labels[lbl] = labels.get(find(lbl), 0)
                x = x2
            else:
                x += 1
        counts = {}
        for px, lbl in cur.items():
            counts[find(lbl)] = counts.get(find(lbl), 0) + 1
        for lbl, c in counts.items():
            labels[lbl] = labels.get(lbl, 0) + c
            biggest = max(biggest, labels[lbl])
        prev = cur
    return biggest, frac


def lint_grid(im: np.ndarray) -> float:
    """Axis-aligned periodicity score restricted to WATER pixels: open water
    should be featureless, so any comb structure in its edge profile is a
    seam artifact (the water2 checkerboard class). The block lattice on
    LAND is honest periodicity and is excluded by the water mask. Returns
    0 when the central band holds too little water to judge."""
    h, w = im.shape[:2]
    crop = im[int(h * 0.35):int(h * 0.80), int(w * 0.15):int(w * 0.85)]
    water = (crop[:, :, 2] > crop[:, :, 1] + 8) & (crop[:, :, 2] > 80)
    if water.mean() < 0.15:
        return 0.0
    lum = crop @ np.array([0.2126, 0.7152, 0.0722])
    score = 0.0
    for axis in (0, 1):
        d = np.abs(np.diff(lum, axis=axis))
        both = water[1:, :] & water[:-1, :] if axis == 0 else water[:, 1:] & water[:, :-1]
        d = np.where(both, d, 0.0)
        prof = d.sum(axis=1 - axis) / (both.sum(axis=1 - axis) + 1)
        prof = prof - prof.mean()
        if prof.std() < 1e-6:
            continue
        ac = np.correlate(prof, prof, mode="full")[len(prof) - 1:]
        ac /= ac[0] + 1e-9
        score = max(score, float(ac[4:96].max()))
    return score


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--accept", action="store_true")
    ap.add_argument("--skip-render", action="store_true")
    args = ap.parse_args()

    viewer = Path(__file__).resolve().parent.parent
    reel = viewer / "interchange" / "reel"
    current = reel / "current"
    accepted = reel / "accepted"
    run_dir = viewer / "interchange" / "runs" / "world-reel"
    play = viewer / "scripts" / "world-reel.play"

    if not args.skip_render:
        build_play(play)
        exe = viewer / "target" / "release" / "examples" / "play.exe"
        r = subprocess.run([str(exe), str(play)], cwd=viewer, capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout[-1500:] + r.stderr[-1500:])
            raise SystemExit(f"reel render failed ({r.returncode})")
        current.mkdir(parents=True, exist_ok=True)
        for name, *_ in ALL_POSES:
            shutil.copyfile(run_dir / f"{name}.png", current / f"{name}.png")

    findings = []
    report = {}
    for name, *_ in ALL_POSES:
        cur_p = current / f"{name}.png"
        if not cur_p.exists():
            findings.append(f"{name}: MISSING current frame")
            continue
        im = np.asarray(Image.open(cur_p).convert("RGB"), dtype=np.float64)
        if name.startswith("moon_"):
            # Space is legitimately black around a moon pose, so Neisor's
            # below-horizon void detector is the wrong invariant. Require a
            # substantial, non-flat generated surface instead.
            lum = im.max(axis=2)
            surface = lum > 45
            surface_frac = float(surface.mean())
            surface_std = float(im[surface].std()) if surface.any() else 0.0
            row = {
                "moon_surface_frac": round(surface_frac, 4),
                "moon_surface_std": round(surface_std, 3),
                "mean_delta": "no-baseline",
            }
            if surface_frac < 0.08:
                findings.append(f"{name}: MOON lint - generated surface missing")
            if surface_std < 5.0:
                findings.append(f"{name}: MOON lint - surface is visually flat")
        else:
            blob, dark_frac = lint_void(np.asarray(Image.open(cur_p).convert("RGB")))
            grid = lint_grid(im)
            row = {"void_blob_px": blob, "dark_frac": round(dark_frac, 5),
                   "grid_score": round(grid, 3)}
            if blob > 400:
                findings.append(f"{name}: VOID lint - {blob}px near-black blob")
        # grid score is INFORMATIONAL for now: healthy scenes carry designed
        # periodicity (block lattice edges, the frozen-ice checker) and the
        # cheap autocorr floor sits too close to the artifact band. The
        # accepted-baseline diff below is the real net for that class;
        # revisit calibration when a live specimen exists again.
        acc_p = accepted / f"{name}.png"
        if acc_p.exists():
            old = np.asarray(Image.open(acc_p).convert("RGB"), dtype=np.float64)
            if old.shape == im.shape:
                d = np.abs(old - im).max(axis=2)
                row["mean_delta"] = round(float(d.mean()), 3)
                row["changed_frac"] = round(float((d > 6).mean()), 4)
                if row["mean_delta"] > CHANGE_MEAN or row["changed_frac"] > CHANGE_FRAC:
                    findings.append(
                        f"{name}: CHANGED vs accepted (mean {row['mean_delta']}, "
                        f"frac {row['changed_frac']})"
                    )
            else:
                row["mean_delta"] = "size-mismatch"
        else:
            row["mean_delta"] = "no-baseline"
        report[name] = row

    (reel / "report.json").parent.mkdir(parents=True, exist_ok=True)
    (reel / "report.json").write_text(json.dumps(report, indent=1), encoding="utf-8")

    if args.accept:
        accepted.mkdir(parents=True, exist_ok=True)
        for name, *_ in ALL_POSES:
            src = current / f"{name}.png"
            if src.exists():
                shutil.copyfile(src, accepted / f"{name}.png")
        print(f"accepted: {len(ALL_POSES)} poses blessed as the reference reel")
        return

    if findings:
        print(f"REEL: {len(findings)} finding(s) to review:")
        for f in findings:
            print(" ", f)
        sys.exit(3)
    print(f"REEL: all {len(ALL_POSES)} poses clean (lint ok, no unexplained change)")


if __name__ == "__main__":
    main()
