"""Export the noise gradient table and golden test values for the Rust port.

The game must evaluate the exact same noise as planetgen (same seed = same
planet), so the Rust side embeds the gradient table and proves equality
against these goldens in `cargo test`.
"""

import json
import sys

sys.path.insert(0, ".")
import numpy as np

from planetgen import noise

# gradient table -> Rust const
lines = ["// Generated by scripts/export_noise_tables.py - do not edit.",
         "pub const GRAD: [[f64; 3]; 256] = ["]
for g in noise._GRAD:
    lines.append(f"    [{float(g[0])!r}, {float(g[1])!r}, {float(g[2])!r}],")
lines.append("];")
with open("viewer/src/noise_grad.rs", "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")

# golden values
rng = np.random.default_rng(12345)
pts = rng.normal(size=(48, 3))
pts /= np.linalg.norm(pts, axis=1, keepdims=True)
cases = [
    dict(kind="gradient", freq=2.5, seed=99),
    dict(kind="fbm", octaves=5, freq=3.0, seed=42),
    dict(kind="fbm", octaves=6, freq=17.6, seed=333059),   # planetgen grit params
    dict(kind="ridged", octaves=5, freq=4.4, seed=2585),
    dict(kind="ridged", octaves=4, freq=22.0, seed=449557),
]
for c in cases:
    if c["kind"] == "gradient":
        c["values"] = noise.gradient_noise(pts * c["freq"], seed=c["seed"]).tolist()
    elif c["kind"] == "fbm":
        c["values"] = noise.fbm(pts, octaves=c["octaves"], freq=c["freq"], seed=c["seed"]).tolist()
    else:
        c["values"] = noise.ridged(pts, octaves=c["octaves"], freq=c["freq"], seed=c["seed"]).tolist()

with open("viewer/tests/noise_golden.json", "w") as f:
    json.dump(dict(points=pts.tolist(), cases=cases), f)
print(f"exported gradient table + {len(cases)} golden cases x {len(pts)} points")
